name = "Texugo"
license = "MIT"
licenselink = "https://github.com/antonioalmeida/texugo-theme/blob/master/LICENSE.md"
description = "Minimalistic website theme based on TeX's typography."
homepage = "https://github.com/antonioalmeida/texugo-theme"
demosite = "https://antonioalmeida.github.io"
tags = ["tex", "personal", "blog", "simple", "clean", "minimalist", "responsive"]
features = ["html5", "css3", "highlight.js", "responsive"]

[author]
  name = "Ant√≥nio Almeida"
  homepage = "https://github.com/antonioalmeida"
